### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by KMax** [semiotproject/simulator-heat-meters#4]
```
[kolchinmax@thinker simulator-heat-meters]$ java -jar target/simulator-heat-meters-1.0-SNAPSHOT-jar-with-dependencies.jar 

    ---------------------------------------
                    MaDKit
               version: 5.0.5.1
            build-id: 20141118-1750
           MaDKit Team (c) 1997-2015
    ---------------------------------------

--------------internal BUG--------------------

-----------------uncaught exception on Thread[Thread-506,4,LIFE@MK-2]
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
    at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
--------------internal BUG--------------------

-----------------uncaught exception on Thread[Thread-455,4,LIFE@MK-2]
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
    at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
--------------internal BUG--------------------

-----------------uncaught exception on Thread[Thread-521,4,LIFE@MK-2]
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
    at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[MadkitKernel-0] FINEST : MadkitKernel-0 (LIVING) launching HeatMeterSPT943_4-304 (NOT_LAUNCHED) by Thread[Thread-555,4,LIFE@MK-2]
[MadkitKernel-0] SEVERE : -*-LIVE BUG*-*
 ** java.lang.OutOfMemoryError: unable to create new native thread
    at madkit.kernel.MadkitKernel.launchConfigAgents(Unknown Source)
    at madkit.kernel.MadkitKernel.startSession(Unknown Source)
    at madkit.kernel.MadkitKernel.live(Unknown Source)

--------------internal BUG--------------------

-----------------uncaught exception on Thread[Thread-602,4,LIFE@MK-2]
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    at madkit.kernel.MadkitKernel.launchAgent(Unknown Source)
    at madkit.kernel.AbstractAgent.launchAgent(Unknown Source)
    at madkit.kernel.MadkitKernel$6.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    ---------------------------------------
             MaDKit Kernel @MK-2 
            is shutting down, Bye !
    ---------------------------------------

Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.network.config.NetworkConfig createStandardWithFile
INFO: Loading standard properties from file Californium.properties
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5001
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
[HeatMeterSPT943_4-190] SEVERE : -*-LIVE BUG*-*
 ** java.lang.OutOfMemoryError: unable to create new native thread
    at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.schedule(SweepDeduplicator.java:151)
    at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.access$100(SweepDeduplicator.java:101)
    at org.eclipse.californium.core.network.deduplication.SweepDeduplicator.start(SweepDeduplicator.java:63)
    at org.eclipse.californium.core.network.Matcher.start(Matcher.java:93)
    at org.eclipse.californium.core.network.CoAPEndpoint.start(CoAPEndpoint.java:262)
    at org.eclipse.californium.core.CoapServer.start(CoapServer.java:192)
    at ru.semiot.simulator.heatmeter.Application.onCreated(Application.java:43)
    at ru.semiot.simulator.heatmeter.TestimonialStore.setData(TestimonialStore.java:46)
    at ru.semiot.simulator.heatmeter.HeatAgent.updateTestimonial(HeatAgent.java:18)
    at ru.semiot.simulator.heatmeter.HeatAgent.live(HeatAgent.java:37)

Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5000
[HeatMeterSPT943_4-270] SEVERE : -*-LIVE BUG*-*
 ** java.lang.OutOfMemoryError: unable to create new native thread
    at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.schedule(SweepDeduplicator.java:151)
    at org.eclipse.californium.core.network.deduplication.SweepDeduplicator$SweepAlgorithm.access$100(SweepDeduplicator.java:101)
    at org.eclipse.californium.core.network.deduplication.SweepDeduplicator.start(SweepDeduplicator.java:63)
    at org.eclipse.californium.core.network.Matcher.start(Matcher.java:93)
    at org.eclipse.californium.core.network.CoAPEndpoint.start(CoAPEndpoint.java:262)
    at org.eclipse.californium.core.CoapServer.start(CoapServer.java:192)
    at ru.semiot.simulator.heatmeter.Application.onCreated(Application.java:43)
    at ru.semiot.simulator.heatmeter.TestimonialStore.setData(TestimonialStore.java:46)
    at ru.semiot.simulator.heatmeter.HeatAgent.updateTestimonial(HeatAgent.java:18)
    at ru.semiot.simulator.heatmeter.HeatAgent.live(HeatAgent.java:37)

[HeatMeterSPT943_4-190] INFO : {0} stopping..
[HeatMeterSPT943_4-270] INFO : {0} stopping..
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5002
[HeatMeterSPT943_4-25] SEVERE : -*-LIVE BUG*-*
 ** java.lang.OutOfMemoryError: unable to create new native thread
    at org.eclipse.californium.elements.UDPConnector.start(UDPConnector.java:116)
    at org.eclipse.californium.core.network.CoAPEndpoint.start(CoAPEndpoint.java:263)
    at org.eclipse.californium.core.CoapServer.start(CoapServer.java:192)
    at ru.semiot.simulator.heatmeter.Application.onCreated(Application.java:43)
    at ru.semiot.simulator.heatmeter.TestimonialStore.setData(TestimonialStore.java:46)
    at ru.semiot.simulator.heatmeter.HeatAgent.updateTestimonial(HeatAgent.java:18)
    at ru.semiot.simulator.heatmeter.HeatAgent.live(HeatAgent.java:37)

[HeatMeterSPT943_4-25] INFO : {0} stopping..
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5003
[HeatMeterSPT943_4-235] SEVERE : -*-LIVE BUG*-*
 ** java.lang.OutOfMemoryError: unable to create new native thread
    at org.eclipse.californium.elements.UDPConnector.start(UDPConnector.java:114)
    at org.eclipse.californium.core.network.CoAPEndpoint.start(CoAPEndpoint.java:263)
    at org.eclipse.californium.core.CoapServer.start(CoapServer.java:192)
    at ru.semiot.simulator.heatmeter.Application.onCreated(Application.java:43)
    at ru.semiot.simulator.heatmeter.TestimonialStore.setData(TestimonialStore.java:46)
    at ru.semiot.simulator.heatmeter.HeatAgent.updateTestimonial(HeatAgent.java:18)
    at ru.semiot.simulator.heatmeter.HeatAgent.live(HeatAgent.java:37)

[HeatMeterSPT943_4-235] INFO : {0} stopping..
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5004
[HeatMeterSPT943_4-170] SEVERE : -*-LIVE BUG*-*
 ** java.lang.OutOfMemoryError: unable to create new native thread
    at org.eclipse.californium.elements.UDPConnector.start(UDPConnector.java:114)
    at org.eclipse.californium.core.network.CoAPEndpoint.start(CoAPEndpoint.java:263)
    at org.eclipse.californium.core.CoapServer.start(CoapServer.java:192)
    at ru.semiot.simulator.heatmeter.Application.onCreated(Application.java:43)
    at ru.semiot.simulator.heatmeter.TestimonialStore.setData(TestimonialStore.java:46)
    at ru.semiot.simulator.heatmeter.HeatAgent.updateTestimonial(HeatAgent.java:18)
    at ru.semiot.simulator.heatmeter.HeatAgent.live(HeatAgent.java:37)

[HeatMeterSPT943_4-170] INFO : {0} stopping..
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.CoapServer start
INFO: Starting server
Mar 10, 2015 2:55:20 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5005
[HeatMeterSPT943_4-123] SEVERE : -*-LIVE BUG*-*
 ** java.lang.OutOfMemoryError: unable to create new native thread
    at org.eclipse.californium.elements.UDPConnector.start(UDPConnector.java:114)
    at org.eclipse.californium.core.network.CoAPEndpoint.start(CoAPEndpoint.java:263)
    at org.eclipse.californium.core.CoapServer.start(CoapServer.java:192)
    at ru.semiot.simulator.heatmeter.Application.onCreated(Application.java:43)
    at ru.semiot.simulator.heatmeter.TestimonialStore.setData(TestimonialStore.java:46)
    at ru.semiot.simulator.heatmeter.HeatAgent.updateTestimonial(HeatAgent.java:18)
    at ru.semiot.simulator.heatmeter.HeatAgent.live(HeatAgent.java:37)

[HeatMeterSPT943_4-123] INFO : {0} stopping..
```

**Comment by KMax** [comment]
I found a fix for this issue and it's related to the limits that exists in any linux machine. If you run `ulimit -a` you will see these limits. To solve this issue we need to increase two limits: `open files` and `max user processes`.

For Fedora:
- open /etc/security/limits.conf and add the following lines to the end:
  
  ```
  *       hard    nofile  64000
  *       soft    nofile  64000
  *       hard    nproc   64000
  *       soft    nproc   64000
  ```
- open /etc/sysctl.conf and add the following line:
  
  ```
  fs.file-max = 64000
  ```
- reboot the machine.

After that `ulimit -a` should show the new values.

**Comment by KMax** [comment]
@soylent-grin and @garayzuev in [this](https://github.com/KMax/californium-examples) repo I've published complete example of a simple simulator running N number of sensors on different ports. GET and OBSERVE methods work as expected, so each COAP-client receive updates only from the sensor it subscribed.

**Comment by KMax** [comment]
@soylent-grin, @garayzuev forget about rewriting the CoAP server for now, but apply the configuration I described above to increase number of threads per process.
